'''
Here we put the name of the constants of the program in german.The same file was created to the english version,
therefore the program will have two differents languages.
'''
#Menu Bar Labels
menuBar_file = 'Datei'
saveAll = 'Alles speichern'
importBU = 'Back-UP importieren'
exportBU = 'Back-UP exportieren'
send_email_to_responsible = 'Back-UP am Verantwortlichen senden'
exit_label = 'Schließen'
menuBar_building = 'Gebaüde'
edit_menuBar = 'Bearbeiten'
verify_room = 'Prüfübersicht der Räume und Mitarbeiten benachrichtigen'
insertItem =  'Gerät hinzufügen'
deleteItem =  'Gerät löschen'
addLocation = 'Orte hinzufügen'
menuBar_grossenMetrawatt = 'Gossen Metrawatt'
importGW = 'Geräte von Gossen Metrawatt importieren'
exportGW = 'Geräte zu Gossen Metrawatt exportieren'
menuBar_help = 'Hilfe'
help_measure = 'Anleitung zum Prüfung'
GW_tutorial_help = 'Anleitung zum Gossen Metrawatt Datenbank'
help_tutorial_2 = "Anleitung zu EPrüfung Software"
help_tutorial_3 = 'Anleitung zum Gossen Metrawatt Importieren/Exportieren'
help_tutorial_4 = 'Anleitung zum automatischen E-Mail'
menuBar_language = 'Sprachen'
english = 'Englisch'
german = 'Deutsch'

# Body Labels
id_body = 'ID'
devices_Body = 'Geräte'
manufacturer_body = 'Hersteller'
serialNumber_body = 'Inventar Nummer'
note_body = 'Bermerkung'
current_Date_Body = 'Datum'
floor_body = 'Stock'
Room_body = 'Raum'
typeRoom_body = 'Raumart:'
office_body = 'Büro'
labor_body = 'Labor'
insertDevice = 'GERÄT EINGEBEN'
deleteDevice =  'GERÄT LÖSCHEN'
saveRoom = 'RAUM SPEICHERN'
floor_2_body = 'Stock bei: '
dataBank_not_compatible = 'Daten Bank nicht kompatibel!!!'

# Titles
title_xml_import = 'Datei importieren .xml'
titleSearch = 'Ergebnisse suchen'
actualizeLink_title = 'Aktualisieren die URL'

# Dialogs
closeBtt = 'Schließ'
problemDetected = 'Problem festgestellt!'
problemDetected_2 = 'Ein Problem wurde festgestellt!'
calenderName = 'Kalender'
calenderSaveOnly = 'Datum für diese Gerät übernehmen'
calenderSaveAll = 'Datum für alle Geräte im Raum übernehmen'
cancelBtt = 'Abbrechen'
newId = 'Neu ID'
newId_Inset = 'Neu ID eingeben:'
newId_Insert_Back = 'Bearbeiten hier'
insert_new_ID = 'Neu ID eingeben'
noRoomDetected = 'Kein Raum detektiert!'
noIdDetected = 'Kein ID detektiert'
negative_ID_message = 'Negativ ID sind nicht möglich!'
id_not_number_error = 'ID ist keine Zahl, bitte, versuch noch einmal!'
id_sheet_error = 'Kein ID detektiert in der Folie!'
message_tutorial_addLocation = 'Die folgenden Anleitungen sollen die Orte der Gossen\nMetrawatt Datenbank zu importieren befolgt werden:\n1) In Gossen Metrawatt muss man einen Ort eingeben oder\n    bearbeiten\n2) Datei soll exportiert werden \n3) Datei soll hier importiert werden.'
processing = 'Es wird bearbeitet'
done= 'Fertig!'
operation_concluded = 'Operation fertig!'
operation_not_concluded = 'Operation nicht fertig!'
file_not_supported = 'Datei nicht lesbar'
backupDayMessage = "Täglich BackUP"
error_message_send_email = '--Outlook ist nicht installiert--'
send_email_to_responsibles = 'E-Mail Entwurf öffnen'
Forgot_to_Save = 'Vergess zu speichern!'
save = 'Speichern'
tableShowResultsHeader_NotVerified_1 = ["Auswählen", "Gebäude", "Stock", "Raum", "Letzte Prüfung"]
tableShowResultsHeader_NotVerified_2 = ["Gebäude", "Stock", "Raum", "E-Mail"]
comboBoxData = ["nicht geprüfte Räume", "geprüfte Räume"]
messageInRed = 'Es gibt keine verfugbare Räume für die ausgewählter Zeitwert'
searchResponsible = "Suchen nach verantwortlichen Personen"
fromlabel = "Von: "
tolabel = "Bis: "
untill = 'Bis: '
choose_appointment = 'Termin wählen:'
error_message_finding_responsibles = 'Fehler detektiert! \nBitte, prüfen Sie die URL'
error_message_finding_responsibles_2 = 'Lehre Tabelle!'
titleEmailSendToResponsibles = 'anstehende Elektrogeräteprüfung'
notFound = 'Nicht gefunden'
actualizeLink = "Aktualisieren die URL der Mitarbeiterliste"
pleaseInsertURLhere = 'Bitte, geben Sie die neue URL ein:'
saved = 'GESPEICHERT'
undo = '&Rückgängig: Eingabe'
ImportWarningMessage = 'Achtung!\nAlle Daten (Gebäude, Räume, Geräte, Prüfdatum) werden\naus der Gossen Metrawatt Datenbank hier importiert und\nüberschrieben.\nHinweis: Zum Importieren von Orten bitte über:\n        Bearbeiten->Orte hinzufügen'
ExportWarningMessage = 'Achtung!\nDie Informationen zu den Geräte (Name, Hersteller, Inventar\nNummer, Bermerkung) werden in das Back-UP der Gossen\nMetrawatt Datenbank exportiert. Das Prüfdatum wird nicht\nexportiert. Das aktuallisiert Back-UP muss anschließend in\ndie Gossen Metrawattt Datenbank wieder importiert werden.'
warning = 'Achtung'